project:
  type: website
  output-dir: docs

website:
  title: "megancoden.github.io"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: cv/index.qmd
        text: CV

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



